<div class="text-center cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
    	<h3 class="masthead-brand"></h3>
      	<img src="<?php echo $_layoutParams['path_media']; ?>img/molecular.png" height="50" class=" masthead-brand d-inline-block align-top" alt="<?php echo APP_NAME; ?>">
      
	    <!-- Menu superior como Widget -->
	    <?php //echo $this->widget_menu_top; ?>

    </div>
  </header>

  <main role="main" class="inner cover">

	<h1 class="cover-heading">Bienvenido a Molecular</h1>
	<p class="lead">Un nuevo, fácil y poderoso framework modular basado en moléculas. </p>
	<span>Ésta página está siendo generada desde:</span>
	<code>views/index/index.phtml </code>
	<span>y el controlador: </span>
	<code>controllers/indexController.php </code>
	<p class="lead">

	</p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Desarrollado por <a href="<?php echo APP_COMPANY_URL; ?>"><?php echo APP_COMPANY; ?></a> - 2022&copy;</p>
    </div>
  </footer>
</div>

