<div class="container px-4 py-5" id="hanging-icons">

<div class="py-5 text-center">   
    <h2>Sucursal Virtual</h2>
    <p class="lead">Conozca cómo administrar sus productos de forma ágil, rápida y segura en nuestros Canales para su servicio.</p>
</div>
    

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Transacciones Bancarias</h2>
          <p>Aquí podrá realizar envíos a otras cuentas.</p>
          <a href="<?php echo BASE_URL.'transfers/own_accounts'; ?>" class="btn btn-outline-secondary">Cuentas Propias</a>
          <a href="<?php echo BASE_URL.'transfers/third_parties'; ?>" class="btn btn-outline-secondary">Cuentas de terceros</a>
          <a href="<?php echo BASE_URL.'transfers/'; ?>" class="btn btn-outline-secondary">Transferencias Realizadas</a>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Estado de la cuenta</h2>
          <p>Revise su cuenta y esté seguro que todo está en orden.</p>
          <a href="#" class="btn btn-outline-secondary">Ver</a>
        </div>
      </div>
    </div>
</div>
