<!-- Error Container -->
<div id="error-container">
    <div class="error-options">
        <h3><i class="fa fa-chevron-circle-left text-muted"></i> <a onclick="history.back()">Atrás</a></h3>
    </div>
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2 text-center">
            <h1 class="animation-pulse"><i class="<?php echo $this->_errorIcon; ?>  animation-pulse"></i> <?php echo $this->_errorCodigo; ?></h1>
            <h2 class="h3"><?php echo $this->_errorMensaje; ?></h2>
        </div>
        <?php if (DEBUG == 'true'): ?>
            <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
                
            </div>
        <?php else: ?>
        <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
            <form action="page_ready_search_results.html" method="post">
                <input type="text" id="search-term" name="search-term" class="form-control input-lg" placeholder="Search ProUI..">
            </form>
        </div>
        <?php endif ?>
    </div>
</div>
<!-- END Error Container -->