<div class="list-group">
    <a href="<?php echo BASE_URL.'transferencias/'; ?>" class="list-group-item list-group-item-action">Transferencias Realizadas</a>
<a href="<?php echo BASE_URL.'transferencias/cuentas_propias'; ?>" class="list-group-item list-group-item-action active">Cuentas Propias</a>
        <a href="<?php echo BASE_URL.'transferencias/terceros'; ?>" class="list-group-item list-group-item-action">Cuentas de terceros</a>
</div>